### ISSUE TITLE
Fixing Docstrings?

### ISSUE THREAD

**Issue by cohensbw** [numericalEFT/Lehmann.jl#36]
Hi, I really like this package you have designed! It offers some really cool functionality that is useful in a wide variety of contexts!
However, looking at the docs, many of the doc strings are not formatted correctly and are rendering improperly.
It is very challenging to read the package API as things stand right now.
Would it be possible to have them fixed?

**Comment by kunyuan** [comment]
Hi, thank you very much for your message and suggestions. We will fix the docs problem as soon as possible.

**Comment by kunyuan** [comment]
Hi, we have just released a significant update v0.2.7.  It has fixed the documentation issues you pointed out. In addition, we added a new set of universal grids that exactly satisfy the time symmetry. Thank you very much for trying our package, and let us know if there are any issues.

**Comment by kunyuan** [comment]
Since the problem has been fixed, I will close this issue. Thank you again!
